# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

### INCLUDES

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations/
#light: !include light.yaml # light groups managed in Deconz
#scene: !include scenes.yaml # scenes are created as scripts
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes

# HTTP Setup
#http:
#  base_url: !secret duckdns_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  ip_ban_enabled: True
#  login_attempts_threshold: 5


### RECORDER, HISTORY AND LOG SETUP

# Log levels
logger:
  default: info
  logs:
    homeassistant.setup: warning
    homeassistant.loader: error
    roomba.roomba.Roomba: warning
    pychromecast.socket_client: error
    homeassistant.components.cast: error
    homeassistant.components.cast.media_player: error
    pychromecast: error
    pychromecast.discovery: error

# Recorder
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 365
  exclude:
    entities:
      - binary_sensor.updater
      - sensor.last_boot
      - automation.health_check

# History
history:
  exclude:
    domains:
      - automation
      - group
      - persistent_notification
      - discovery
      - history_graph


### INTEGRATIONS

# InfluxDB configuration
influxdb:
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor

# Health check: https://healthchecks.io/
rest_command:
  health_check:
    url: !secret health_check_url

# Telegram Bot (polling method)
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chatid

# Notify components
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chatid

# Spotify
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# Circadian lightning for lights (HACS custom component), currently not used
# circadian_lighting:

### SWITCHES ###
switch:
  - platform: template
    switches:
      ac:
        friendly_name: "AC"
        value_template: "{{ is_state('climate.air_conditioner', 'heat_cool') or is_state('climate.air_conditioner', 'heat') or is_state('climate.air_conditioner', 'dry') or is_state('climate.air_conditioner', 'fan_only') or is_state('climate.air_conditioner', 'cool') }}"
        turn_on:
          - service: climate.set_temperature
            entity_id: climate.air_conditioner
            data:
              temperature: '23'
          - service: climate.set_fan_mode
            entity_id: climate.air_conditioner
            data:
              fan_mode: 'auto'
          - service: climate.set_hvac_mode
            data:
              entity_id: climate.air_conditioner
              hvac_mode: 'heat_cool'
          - service: climate.set_swing_mode
            entity_id: climate.air_conditioner
            data:
              swing_mode: '3'
        turn_off:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.air_conditioner
            hvac_mode: 'off'
      roomba:
        friendly_name: "Roomba"
        value_template: "{{ is_state('vacuum.watson', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          entity_id: vacuum.watson
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.watson

### INPUT BOOLEANS ###
input_boolean:
  guest_mode:
    name: "Guest mode"
    icon: mdi:account-multiple
  vacation_mode:
    name: "Vacation mode"
    icon: mdi:beach
  sleeping:
    name: "Sleeping"
    icon: mdi:sleep

### SENSORS ###
binary_sensor:
  - platform: template
    sensors: 
      occupancy:
        value_template: "{{ is_state('group.people', 'home') }}"

sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 1
    period: 300
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_15m
      - type: processor_use
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Outside temperature"
        unit_of_measurement: '°C'
        value_template: "{{states.weather.home.attributes.temperature}}"
      ac_state:
        friendly_name: "Air Conditioner state"
        #unit_of_measurement: 'Mode'
        value_template: "{{states.climate.air_conditioner.state}}"
      living_room_sensor_battery:
        friendly_name: Xiaomi Mijia battery
        unit_of_measurement: '%'
        value_template: "{{states.sensor.mi_t_582d34345074.attributes.battery_level}}"
  - platform: command_line
    name: "CPU Temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | round(1) }}'