### SUMMER / COOL ###

- alias: "AC to cool mode"
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_582d34345074
      above: 25
      for: "00:15:00"
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: '{{ now().month >= 5 and now().month <= 9 }}'
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'off'
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.occupancy
              state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'on'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '23'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '1_up'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'cool'

- alias: "AC off when target temperature reached"
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_582d34345074
      below: 24.4
      for: "02:00:00"
  condition:
    - condition: template
      value_template: '{{ now().month >= 5 and now().month <= 9 }}'
    - condition: state
      entity_id: switch.ac
      state: 'on'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'off'


### WINTER / HEAT ###

- alias: "AC to comfort heat occupancy"
  trigger: 
    platform: state
    entity_id: binary_sensor.occupancy
    to: 'on'
  condition:
    condition: template
    value_template: '{{ now().month >= 10 or now().month <= 4 }}'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '20.5'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '4'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'

- alias: "AC to comfort heat in the morning"
  trigger: 
    platform: time
    at: '06:00:00'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: '{{ now().month >= 10 or now().month <= 4 }}'
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.occupancy
              state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'on'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '20.5'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '4'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'
    
- alias: "AC to economical heat occupancy"
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy
      to: 'off'
      for: '00:30:00'
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'
  condition: 
    - condition: template
      value_template: '{{ now().month >= 10 or now().month <= 4 }}'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '18'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '4'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'

- alias: "AC to economical heat for the night"
  trigger:
    platform: time
    at: '20:00:00'
  condition: 
    condition: template
    value_template: '{{ now().month >= 10 or now().month <= 4 }}'
  action: 
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '18'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '4'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'

- alias: "AC off during winter if warm enough" # practically due to fireplace or warm outside
  trigger:
    platform: numeric_state
    entity_id: sensor.ble_temperature_582d34345074
    above: 23.5
    for: "00:15:00"
  condition: 
    - condition: template
      value_template: '{{ now().month >= 10 or now().month <= 4 }}'
    - condition: state
      entity_id: switch.ac
      state: 'on'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'off'
    - service: automation.turn_off
      entity_id: 
        - automation.ac_to_comfort_heat_in_the_morning
        - automation.ac_to_comfort_heat_occupancy
        - automation.ac_to_economical_heat_for_the_night
        - automation.ac_to_economical_heat_occupancy

- alias: "AC back to comfort heat during winter if cold enough"
  trigger:
    platform: numeric_state
    entity_id: sensor.ble_temperature_582d34345074
    below: 23.5
    for: "00:30:00"
  condition: 
    - condition: template
      value_template: '{{ now().month >= 10 or now().month <= 4 }}'
    - condition: state
      entity_id: switch.ac
      state: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '20'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '4'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'
    - service: automation.turn_on
      entity_id: 
        - automation.ac_to_comfort_heat_in_the_morning
        - automation.ac_to_comfort_heat_occupancy
        - automation.ac_to_economical_heat_for_the_night
        - automation.ac_to_economical_heat_occupancy