# TURN ON AC COLD #

- alias: "Turn on AC when it's too cold"
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_t_582d34345074
    below: 22.6 #19
    for: "00:10:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '23'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '5_down'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'heat'

# TURN ON AC HOT #

- alias: "Turn on AC when it's too hot"
  trigger:
    - platform: numeric_state
      entity_id: sensor.mi_t_582d34345074
      above: 25 # 30 degrees during Winter, due to fireplace
      for: "00:10:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.air_conditioner
      data:
        temperature: '23'
    - service: climate.set_fan_mode
      entity_id: climate.air_conditioner
      data:
        fan_mode: 'auto'
    - service: melcloud.set_vane_horizontal
      entity_id: climate.air_conditioner
      data:
        position: '3'
    - service: melcloud.set_vane_vertical
      entity_id: climate.air_conditioner
      data:
        position: '1_up'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'cool'

# TURN AC OFF #

- alias: "Turn off AC when target temperature is reached"
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_t_582d34345074
    below: 24.4 #26 winter
    above: 23
    for: "00:30:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.air_conditioner
          state: 'off'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.air_conditioner
        hvac_mode: 'off'