- alias: "Turn off bedroom lights automatically"
  trigger: 
    platform: state
    entity_id: binary_sensor.bedroom_motion_sensor
    to: 'off'
    for: '00:10:00'
  condition:
    condition: state
    entity_id: input_boolean.bedroom_presence
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights
      transition: 15

- alias: "Turn off bedroom presence automatically"
  trigger: 
    platform: state
    entity_id: input_boolean.bedroom_presence
    to: 'on'
    for: '02:00:00'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.bedroom_presence
    
- alias: "Flash bedroom lights if either door is opened during the night"
  trigger: 
    - platform: state
      entity_id: binary_sensor.frontdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.backdoor
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action: 
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 100
        flash: long
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Joku avasi ulko-oven!'
        language: 'fi'

- alias: "Set bedroom color temperature and brightness"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: >
          {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
            80
          {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
            60
          {% else %}
            20
          {% endif %}
    - service: light.turn_on
      data:
        entity_id: light.bedroom_spotlights
        kelvin: > 
          {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
            4000
          {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
            2700
          {% else %}
            2200
          {% endif %}
    - delay: "00:00:01"
    - service: light.turn_on
      data:
        entity_id: light.bedroom_spotlights
        brightness_pct: >
          {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
            80
          {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
            60
          {% else %}
            20
          {% endif %}
    