- alias: 'Bedroom lights remote'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
  action:
    - choose: 
      # Toggle bedroom lights
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: light.toggle
            data:
              entity_id: light.bedroom_lights
      # Increase brightness of bedroom lights
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.bedroom_lights
              brightness: >
                {% set bri = state_attr('light.bedroom_lights', 'brightness') | int %}
                {{ [bri+50, 255] | min }}
      # Decrease brightness of bedroom lights
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.event == 3002 }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.bedroom_lights
              brightness: >
                {% set bri = state_attr('light.bedroom_lights', 'brightness') | int %}
                {{ [bri-50, 1] | max }}
      # Set color temperature of bedroom lights to warmer
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.event == 5002 }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.bedroom_lights
              color_temp: >
                {% set mired = state_attr('light.bedroom_lights', 'color_temp') | int %}
                {% if mired < 251 %} 370
                {% elif mired > 250 and mired < 371 %} 455
                {% else %} 250 {% endif %}
      # Set color temperature of bedroom lights to colder
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.event == 4002 }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.bedroom_lights
              color_temp: >
                {% set mired = state_attr('light.bedroom_lights', 'color_temp') | int %}
                {% if mired > 454 %} 370
                {% elif mired > 250 and mired < 371 %} 250
                {% else %} 455 {% endif %}