- alias: "Turn on bedroom lights when motion sensor triggered"
  initial_state: true
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_23
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 150
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: time
      before: '02:00:00'
      after: '07:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness_pct: >
          {% if 5 <= now().hour < 18 %}
            99
          {% elif 18 <= now().hour < 21 %}
            75
          {% else %}
            40
          {% endif %}
        kelvin: >
          {% if 5 <= now().hour < 18 %}
            4000
          {% elif 18 <= now().hour < 21 %}
            2700
          {% else %}
            2200
          {% endif %}
    - delay: '00:10:00'

- alias: "Turn off bedroom lights 10 minutes after last movement"
  initial_state: true
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_23
    to: 'off'
    for: '00:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights
      #transition: 10

- alias: "Flash bedroom lights if either door is opened during the night"
  trigger: 
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
    - platform: state
      entity_id: binary_sensor.openclose_15
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action: 
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 100
        flash: long
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Joku avasi ulko-oven!'
        language: 'fi'

  
- alias: "Set bedroom temperature and brightness in the morning and day"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'night_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_1'
      - condition: state
        entity_id: sensor.daylight
        state: 'solar_noon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        kelvin: 4000
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 80

- alias: "Set bedroom temperature and brightness in the evening"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_2'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'night_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'nadir'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        kelvin: 2200
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 20