- alias: "Turn on bedroom lights when motion sensor triggered"
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_23
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 150
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: time
      before: '02:00:00'
      after: '07:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness_pct: >
          {% if 5 <= now().hour < 18 %}
            99
          {% elif 18 <= now().hour < 21 %}
            75
          {% else %}
            40
          {% endif %}
        kelvin: >
          {% if 5 <= now().hour < 18 %}
            4000
          {% elif 18 <= now().hour < 21 %}
            2700
          {% else %}
            2200
          {% endif %}

- alias: "Turn off bedroom lights 5 minutes after last movement"
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_23
    to: 'off'
    for: '00:05:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights
      #transition: 10

- alias: "Flash bedroom lights if either door is opened during the night"
  trigger: 
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
    - platform: state
      entity_id: binary_sensor.openclose_15
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action: 
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 100
        flash: long
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Joku avasi ulko-oven!'
        language: 'fi'