- alias: "Turn on bedroom lights when motion sensor triggered"
  trigger: 
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 80
    - condition: time
      after: '21:00:00'
      before: '23:59:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 20
        rgb_color: [255,182,109]
    - delay: '00:15:00'
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lights
        transition: 10


- alias: "Flash bedroom lights if either door is opened during the night"
  trigger: 
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
    - platform: state
      entity_id: binary_sensor.openclose_15
      to: 'on'
  condition:
    - condition: time
      after: '23:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
  action: 
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 100
        flash: long
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Joku avasi ulko-oven!'
        language: 'fi'

# DURING THE DAY

- alias: "Set bedroom lights brightness to max when turned on during the day"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'night_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_1'
      - condition: state
        entity_id: sensor.daylight
        state: 'solar_noon'
  action:
    - delay: '00:00:01'
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 80
        kelvin: 2700


# DURING THE EVENING

- alias: "Set bedroom lights brightness when turned on during the evening"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_2'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dusk'
  action:
    - delay: '00:00:01'
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 20
        kelvin: 2200