- alias: 'Toggle bedroom lights'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 1002
  action:
    service: light.toggle
    entity_id: light.bedroom_lights

- alias: 'Increase brightness of bedroom lights from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness: >
          {% set bri = state_attr('light.bedroom_lights', 'brightness') | int %}
          {{ [bri+50, 255] | min }}

- alias: 'Decrease brightness of bedroom lights from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness: >
          {% set bri = state_attr('light.bedroom_lights', 'brightness') | int %}
          {{ [bri-50, 1] | max }}

- alias: 'Set color temperature of bedroom lights to warmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 5002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        color_temp: >
          {% set mired = state_attr('light.bedroom_lights', 'color_temp') | int %}
          {% if mired < 251 %} 370
          {% elif mired > 250 and mired < 371 %} 455
          {% else %} 250 {% endif %}

- alias: 'Set color temperature of bedroom lights to colder'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_remote
      event: 4002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        color_temp: >
          {% set mired = state_attr('light.bedroom_lights', 'color_temp') | int %}
          {% if mired > 454 %} 370
          {% elif mired > 250 and mired < 371 %} 250
          {% else %} 455 {% endif %}