# DURING THE DAY

- alias: "Set bedroom lights brightness to max when turned on during the day"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    from: 'unavailable'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'night_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_1'
      - condition: state
        entity_id: sensor.daylight
        state: 'solar_noon'
  action:
    - delay: '00:00:01'
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 80
        kelvin: 2700


# DURING THE EVENING

- alias: "Set bedroom lights brightness when turned on during the evening"
  trigger:
    platform: state
    entity_id: light.bedroom_light_1
    from: 'unavailable'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_2'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dusk'
  action:
    - delay: '00:00:01'
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 20
        kelvin: 2200