- alias: "Bedtime routine"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_button
      event: 1001
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.sleeping
      transition: 10