- alias: "Bedtime routine"
  trigger: 
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'on'
    - condition: time
      after: '21:00:00'
      before: '23:59:00'
  action:
    - service: automation.turn_off
      entity_id: automation.bedtime_routine
    - service: automation.turn_on
      entity_id: automation.morning_routine
    - service: light.turn_on
      data:
        entity_id: light.hallway_lights
        brightness_pct: 10
        transition: 1
    - service: light.turn_off
      data:
        entity_id: light.hallway_lights
        transition: 3600
    - service: light.turn_off
      data:
        entity_id: light.living_room_lights
        transition: 3600
    - service: light.turn_off
      data:
        entity_id: light.hallway_upstairs_lights
        transition: 10800
    - service: sonos.set_sleep_timer
      data:
        entity_id: media_player.living_room
        sleep_time: 5400