- alias: "Bedtime routine"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_button
      event: 1002
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    - service: script.turn_on
      data:
        entity_id: script.sleeping_scene
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Hyvää yötä!'
        language: 'fi'