- alias: "Bedtime routine"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_button
      event: 1001
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    - service: automation.turn_off
      entity_id: 
        - automation.turn_on_bedroom_lights_when_motion_sensor_triggered
        - automation.set_bedroom_lights_brightness_when_turned_on_during_the_day
        - automation.set_bedroom_lights_brightness_when_turned_on_during_the_evening
    - service: scene.turn_on
      data:
        entity_id: scene.sleeping
        transition: 10
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: 'Hyvää yötä!'
        language: 'fi'
    - delay: '00:00:15'
    - service: automation.turn_on
      entity_id: 
        - automation.turn_on_bedroom_lights_when_motion_sensor_triggered
        - automation.set_bedroom_lights_brightness_when_turned_on_during_the_day
        - automation.set_bedroom_lights_brightness_when_turned_on_during_the_evening