# DURING THE DAY

- alias: "Set lights brightness to max when turned on during the day"
  trigger:
    platform: state
    entity_id: 
      - light.tripod_lamp
      - light.hallway_light_1
      - light.hallway_light_2
      - light.hallway_light_3
      - light.hallway_light_4
      - light.hallway_upstairs_light_1
      - light.hallway_upstairs_light_2
      - light.hallway_upstairs_light_3
      - light.bedroom_light_1
      - light.bedroom_light_2
      - light.bedroom_light_3
    from: 'unavailable'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'night_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_1'
      - condition: state
        entity_id: sensor.daylight
        state: 'solar_noon'
  action:
    service: light.turn_on
    data_template:
      entity_id: '{{trigger.entity_id}}'
      brightness_pct: 100
      kelvin: 4000


# DURING THE EVENING

- alias: "Set lights brightness when turned on during the evening"
  trigger:
    platform: state
    entity_id: 
      - light.tripod_lamp
      - light.hallway_light_1
      - light.hallway_light_2
      - light.hallway_light_3
      - light.hallway_light_4
      - light.hallway_upstairs_light_1
      - light.hallway_upstairs_light_2
      - light.hallway_upstairs_light_3
      - light.bedroom_light_1
      - light.bedroom_light_2
      - light.bedroom_light_3
    from: 'unavailable'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_2'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dusk'
  action:
    service: light.turn_on
    data:
      entity_id: '{{trigger.entity_id}}'
      brightness_pct: 80
      kelvin: 2700