- alias: "Dim tripod lamp in the evening if on"
  trigger:
    platform: time
    at: '21:00'
  condition:
    condition: state
    entity_id: light.tripod_lamp
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.tripod_lamp
      brightness_pct: 60
      transition: 15

- alias: "Dim hallway lights in the evening if on"
  trigger:
    platform: time
    at: '19:30'
  condition:
    condition: state
    entity_id: light.hallway_lights
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.hallway_lights
      brightness_pct: 60
      transition: 15

- alias: "Dim upstairs hallway lights in the evening if on"
  trigger:
    platform: time
    at: '19:30'
  condition:
    condition: state
    entity_id: light.hallway_upstairs_lights
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.hallway_upstairs_lights
      brightness_pct: 60
      transition: 15