- alias: "Laundry room lights on"
  trigger: 
    platform: state
    entity_id: binary_sensor.laundry_room_motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lights
      brightness_pct: >
        {% if 6 <= now().hour < 21 %}
          100
        {% else %}
          60
        {% endif %}

- alias: "Laundry room lights off"
  trigger: 
    platform: state
    entity_id: binary_sensor.laundry_room_motion_sensor
    to: 'off'
    for: '00:05:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.laundry_room_lights
      transition: 15