- alias: "Laundry room lights on"
  trigger: 
    platform: state
    entity_id: binary_sensor.laundry_room_motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.laundry_room_lights
      brightness_pct: 100
      transition: 5

- alias: "Laundry room lights off"
  trigger: 
    platform: state
    entity_id: binary_sensor.laundry_room_motion_sensor
    to: 'off'
    for: '00:05:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.laundry_room_lights
      transition: 15