- alias: "Turn on lights if dark during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.motion_sensor_2
    below: 80
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: binary_sensor.occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    service: script.turn_on
    data:
      entity_id: >
        {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
          script.daytime_scene
        {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
          script.evening_scene
        {% else %}
          script.night_scene
        {% endif %}
      transition: 15

- alias: "Turn off lights if bright during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.motion_sensor_2
    above: 110
    for: "00:03:00"
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  action:
    service: script.turn_on
    data:
      entity_id: script.daytime_bright_scene
      transition: 15