- alias: "Turn on lights if dark during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.lightlevel_5
    below: 50
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: person.tuomas_pakkanen
          state: 'home'
        - condition: state
          entity_id: person.moona
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.tripod_lamp
        brightness_pct: 90
        transition: 30
    - service: light.turn_on
      data:
        entity_id: light.hallway_lights
        brightness_pct: 90
        transition: 30
    - service: light.turn_on
      data:
        entity_id: light.hallway_upstairs_lights
        brightness_pct: 90
        transition: 30


- alias: "Turn off lights if bright during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.lightlevel_5
    above: 100
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'on'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room_lights
        transition: 30
    - service: light.turn_off
      data:
        entity_id: light.hallway_lights
        transition: 30
    - service: light.turn_off
      data:
        entity_id: light.hallway_upstairs_lights
        transition: 30