- alias: "Change tripod lamp temperature in the evening"
  trigger:
    platform: time
    at: '19:00'
  condition:
    condition: state
    entity_id: light.tripod_lamp
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.tripod_lamp
      kelvin: 2700
      transition: 15