- alias: "Turn on lights if dark during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.motion_sensor_2
    below: 80
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: binary_sensor.occupancy
      state: 'on'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.daytime
      transition: 30


- alias: "Turn off lights if bright during the day"
  trigger:
    platform: numeric_state
    entity_id: sensor.motion_sensor_2
    above: 110
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'on'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.daytime_bright
      transition: 30