- alias: "Turn off living room lights 30 minutes after last movement"
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_20
    to: 'off'
    for: '00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: time
      after: '20:00:00'
      before: '02:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room_lights
        transition: 10
    - service: light.turn_off
      data:
        entity_id: light.hallway_lights
        transition: 10