- alias: "Turn off living room lights 60 minutes after last movement"
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_20
    to: 'off'
    for: '01:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room_lights
      transition: 10