- alias: "Turn off media room lights when TV turned off"
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    to: 'off'
    for: '00:02:00'
  condition:
    condition: time
    after: '20:00:00'
    before: '03:00:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.media_room_lights
      transition: 10

- alias: "Set media room temperature and brightness in the morning and day"
  trigger:
    platform: state
    entity_id: light.media_room_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'night_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'dawn'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunrise_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_1'
      - condition: state
        entity_id: sensor.daylight
        state: 'solar_noon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        kelvin: 4000
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        brightness_pct: 80

- alias: "Set media room temperature and brightness in the evening"
  trigger:
    platform: state
    entity_id: light.media_room_light_1
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.daylight
        state: 'golden_hour_2'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'sunset_end'
      - condition: state
        entity_id: sensor.daylight
        state: 'dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'night_start'
      - condition: state
        entity_id: sensor.daylight
        state: 'nautical_dusk'
      - condition: state
        entity_id: sensor.daylight
        state: 'nadir'
  action:
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        kelvin: 2200
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        brightness_pct: 20