- alias: "Turn off media room lights when TV turned off"
  trigger:
    platform: state
    entity_id: media_player.sony_bravia_tv
    to: 'off'
    for: '00:05:00'
  condition:
    condition: time
    after: '20:00:00'
    before: '03:00:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.media_room_lights
      transition: 10

- alias: "Set media room color temperature and brightness"
  trigger:
    platform: state
    entity_id: light.media_room_light_1
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        kelvin: > 
          {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
            4000
          {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
            2700
          {% else %}
            2200
          {% endif %}
    - delay: "00:00:01"
    - service: light.turn_on
      data:
        entity_id: light.media_room_lights
        brightness_pct: >
          {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
            80
          {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
            60
          {% else %}
            20
          {% endif %}