- alias: "Morning routine"
  trigger: 
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:00:00'
    before: '12:00:00'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {%-if states('sensor.motion_sensor_2') | float < 80 %}
            scene.daytime
          {%- else %}
            scene.daytime_bright
          {%- endif %}
        transition: 5
    - service: tts.google_translate_say
      entity_id: media_player.living_room
      data:
        message: 'Hyvää huomenta!'
        language: 'fi'
    - delay: '00:00:05'
    - service: media_player.select_source
      data: 
        entity_id: media_player.living_room
        source: 'Yle Radio Suomi'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room
        volume_level: 0.15
    - service: media_player.turn_on
      data:
        entity_id: media_player.living_room
    - service: automation.turn_on
      entity_id: automation.bedtime_routine
    - service: automation.turn_off
      entity_id: automation.morning_routine