- alias: "Morning routine"
  trigger: 
    platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '08:00:00'
    before: '12:00:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
        - light.hallway_upstairs_lights
        - light.hallway_lights
        transition: 5
        brightness_pct: >
          {% if states('sensor.motion_sensor_2') | float < 80 %}
            100
          {% else %}
            0
          {% endif %}
    - service: light.turn_on
      data_template:
        entity_id: light.tripod_lamp
        transition: 5
        kelvin: 4000
        brightness_pct: >
          {% if states('sensor.motion_sensor_2') | float < 80 %}
            100
          {% else %}
            0
          {% endif %}
    - service: tts.google_translate_say
      entity_id: media_player.living_room
      data:
        message: 'Hyvää huomenta!'
        language: 'fi'
    - delay: '00:00:05'
    - service: media_player.select_source
      data: 
        entity_id: media_player.living_room
        source: 'Yle Radio Suomi'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room
        volume_level: 0.15
    - service: media_player.turn_on
      data:
        entity_id: media_player.living_room
    - service: automation.turn_on
      entity_id: automation.bedtime_routine
    - service: automation.turn_off
      entity_id: automation.morning_routine