# SAUNA #

- alias: "Notify when Sauna is warm"
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_5
    above: 50
  action:
    service: notify.telegram
    data:
      message: "Sauna is ready!"

# BURGLAR ALARM

- alias: "Burglar alarm"
  trigger: 
    platform: state
    entity_id:
      - binary_sensor.openclose_14
      - binary_sensor.openclose_15
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.occupancy
    state: 'off'
  action:
    service: notify.telegram
    data:
      title: "Burglar alarm triggered!"
      message: "{{trigger.entity_id}} has been opened"

# SYSTEM #

- alias: "Health check"
  trigger:
    platform: time_pattern
    minutes: "/15"
  action:
    service: rest_command.health_check

- alias: "CPU Temperature too high"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: 75
    for: "00:02:00"
  action:
    service: notify.telegram
    data:
      title: "System alert!"
      message: "Raspberry Pi CPU temperature critical! Current temperature is {{ states('sensor.cpu_temperature') }}°C"

- alias: "Disk usage exceeded 80 percent"
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent
    above: 80.0
  action:
    service: notify.telegram
    data:
      title: "System alert!"
      message: "Raspberry Pi free disk space running low!"

# BATTERY WARNINGS #

- alias: "Xiaomi temperature sensor battery low"
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_sensor_battery
    below: 15
  action:
    service: notify.telegram
    data:
      title: '*Battery low alert!*'
      message: "Xiaomi Mijia temperature and humidity sensor battery is running low. Please replace the battery."

- alias: "Hue motion sensor battery low"
  trigger:
    platform: numeric_state
    entity_id: sensor.motion_sensor_battery_level
    below: 15
  action:
    service: notify.telegram
    data:
      title: '*Battery low alert!*'
      message: "Hue motion sensor battery is running low. Please replace the battery."