- alias: "Set evening scene"
  trigger:
    platform: time
    at: input_datetime.evening_start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.occupancy
            state: 'on'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.evening_scene
      transition: 15

- alias: "Set night scene"
  trigger:
    platform: time
    at: input_datetime.night_start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.occupancy
            state: 'on'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.night_scene
      transition: 15

- alias: 'Fireplace scene activated'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: [script.fireplace_scene]
      domain: script
      service: turn_on
  action:
    - service: automation.turn_off
      entity_id: automation.set_evening_scene
    - service: automation.turn_off
      entity_id: automation.set_night_scene
    - service: automation.turn_off
      entity_id: automation.Turn_on_lights_if_dark_during_the_day
    - delay: '03:00:00'
    - service: automation.turn_on
      entity_id: automation.set_evening_scene
    - service: automation.turn_on
      entity_id: automation.set_night_scene
    - service: automation.turn_on
      entity_id: automation.Turn_on_lights_if_dark_during_the_day
