- alias: "Set evening start time"
  trigger: 
    platform: sun
    event: sunset
  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.evening_start
      data:
        time: "{{ now().strftime('%H:%M:%S') }}"

- alias: "Set evening scene"
  trigger:
    platform: time
    at: input_datetime.evening_start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        after: "14:00:00"
        before: input_datetime.night_start
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.occupancy
            state: 'on'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.evening_scene

- alias: "Set night scene"
  trigger:
    platform: time
    at: input_datetime.night_start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.occupancy
            state: 'on'
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    service: script.turn_on
    data:
      entity_id: script.night_scene