- alias: "Set evening scene"
  trigger:
    platform: time
    at: '19:30:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.occupancy
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.evening
      transition: 15