- alias: "Set evening scene"
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.occupancy
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 80
  action:
    service: scene.turn_on
    data:
      entity_id: scene.evening
      transition: 15