- alias: "Turn on lights when coming home if it's dark"
  trigger: 
    - platform: state
      entity_id: person.tuomas_pakkanen
      to: 'home'
    - platform: state
      entity_id: person.moona
      to: 'home'
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 80
  action:
    service: script.turn_on
    data:
      entity_id: >
        {% if 7 <= now().hour < state_attr('input_datetime.evening_start', 'hour') %}
          script.daytime_scene
        {% elif state_attr('input_datetime.evening_start', 'hour') <= now().hour < state_attr('input_datetime.night_start', 'hour') %}
          script.evening_scene
        {% else %}
          script.night_scene
        {% endif %}