- alias: "Turn on lights when coming home if it's dark"
  trigger: 
    - platform: state
      entity_id: person.tuomas_pakkanen
      to: 'home'
    - platform: state
      entity_id: person.moona
      to: 'home'
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 80
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if 7 <= now().hour < 19 %}
          scene.daytime
        {% elif 19 <= now().hour < 21 %}
          scene.evening
        {% else %}
          scene.night
        {% endif %}
      transition: 5