- alias: "Turn on lights for a while during the night if coming downstairs"
  trigger: 
    platform: state
    entity_id: binary_sensor.presence_3
    to: 'on'
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: time
      after: '21:00:00'
      before: '23:59:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.tripod_lamp
        brightness_pct: 70
        kelvin: 2200
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.hallway_lights
        brightness_pct: 10
        transition: 5
    - delay: '00:10:00'
    - service: light.turn_off
      data:
        entity_id: light.tripod_lamp
        transition: 15
    - service: light.turn_off
      data:
        entity_id: light.hallway_lights
        transition: 15