- alias: "Turn on lights for a while when coming home during the night"
  trigger: 
    - platform: state
      entity_id: person.tuomas_pakkanen
      to: 'home'
    - platform: state
      entity_id: person.moona
      to: 'home'
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.evening
        transition: 5
    - delay: '00:15:00'
    - service: scene.turn_on
      data:
        entity_id: scene.sleeping
        transition: 5