- alias: "Turn on table lamp on sunset"
  trigger: 
    platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
    - condition: state
      entity_id: light.table_lamp
      state: 'off'
    - condition: time
      after: '14:00:00'
      before: '21:00:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: person.tuomas_pakkanen
          state: 'home'
        - condition: state
          entity_id: person.moona
          state: 'home'
  action:
    service: light.turn_on
    data:
      entity_id: light.table_lamp
      kelvin: 2700
      brightness_pct: 80
      transition: 15