- alias: "Turn on lights when coming home if it's dark"
  trigger: 
    - platform: state
      entity_id: binary_sensor.occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.openclose_14
      to: 'on'
  condition:
    - condition: state
      entity_id: light.tripod_lamp
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.motion_sensor_2
      below: 80
    - condition: time
      after: '12:00:00'
      before: '21:00:00'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {%-if 12 <= now().hour < 19 %}
          scene.daytime
        {%- else %}
          scene.evening
        {%- endif %}
      transition: 5