- alias: "Turn off lights and music when leaving home"
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: all
    - service: sonos.set_sleep_timer
      data:
        entity_id: media_player.living_room
        sleep_time: 0